# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac0cc7597f35d499b734cb1a8c861f1523e24c3023825ab578f6f118550ec6d5b79202755a0d053af05e75c492e09a95d4639447a19e6e06f629bd45c530c5e

test:
  secret_key_base: 50d40e3bddcdcb386027694da1cec495c200ae16259bd4d69e5e2e4378e4e8f86aa04c08abb0b398a7a6d296523a3f001ea3763e81a4805c87944c1c45815b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
